---
# tasks file for logstash
- name: Install Java
  apt:
    name: default-jre
    state: latest
    force_apt_get: yes
    update_cache: yes
  tags: logstash

- name: Install Logstash
  apt:
    name: logstash
    state: latest
    force_apt_get: yes
  tags: logstash

- name: Start Logstash at boot time
  service:
    name: logstash.service
    state: started
    enabled: yes
  tags: logstash

- name: Verify if Logstash Pipeline configuration file exists
  stat:
    path: /etc/logstash/conf.d/01-logstash.conf
  register: st
  tags: logstash

- name: Install configuration file
  copy:
    src: 01-logstash.conf
    dest: /etc/logstash/conf.d
    mode: 0644
  when: st.stat.exists == False
  notify: "Restart Logstash"
  tags: logstash
...
