---
- name: Deploy the Elastic Stack
  hosts: vm1
  become: yes

  roles:
  - common
  - elastic_search
  - kibana
  - logstash

- name: Deploy the Elastic Stack (Beats)
  hosts: vm2
  become: yes

  roles:
  - common
  - beats
...
