---
# tasks file for kibana
- name: Install Kibana
  apt:
    name: kibana
    state: latest
    force_apt_get: yes
    update_cache: yes
  tags: kibana

- name: Deploy Kibana configuration file
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
  notify: "Restart Kibana"
  tags: kibana

- name: Start Kibana at boot time
  service:
    name: kibana.service
    state: started
    enabled: yes
  tags: kibana
...
